new Vue({
    el:".article",
    data:{
        //头部模块
        signout:true,
        isLogin:false,
        uname:"",
        search_text:"",
        //轮播模块
        list:[],
        left:0,
        nextLeft:0,
        time:0,
        transitionTime:1000,
        pno:0,
        intervalTime:6000,
        isHover:false,
        //商品模块
        proTitle:[],
        proList:[],
        toastList:[],
        giftList:[],
        carCount:"",
        isaddcart:false,
        carCake:{title:"",price:"",taste:"",spec:"",sweet:"",kg:"",},
        cartBg:false,
        success:false,
        //加载
        loadBanner:false,
        loadProduct:false,
        loadF1:false,
        loadF2:false,
        loadComment:false,
        loadFooter:false,
    },
    created(){
        axios.get("http://localhost:3000/user/islogin")
        .then((res)=>{
            var res=res.data
            if(res.ok==0){
                this.signout=true
                this.isLogin=false
            }else{
                this.signout=false
                this.isLogin=true
                this.uname=res.uname
            }
        })
    },
    mounted(){
        this.getImg()
        this.getCarCount()
    },
    methods:{
    //头部模块
        goLogin(){
            var url=location.href
            location.href="http://localhost:3000/login.html?back="+url
        },
        signOut(){
            axios.get("http://localhost:3000/user/signout")
            .then((res)=>{
                location.reload(true)
            })
        },
        myIndent(){
            if(this.isLogin==true){
                location.href="index.html"
            }else{
                location.href="login.html"
            }
        },
        search(){
            var str=this.search_text
            str = str.replace(/\s*/g,"");
            if(str=="")
            str="雪域"
            location.href="product-search.html?kw="+str
        },
        shoppingCart(){
            if(this.isLogin==true){
                location.href="http://localhost:3000/shopping-car.html"
            }else{
                alert("请先登录")
                var url=location.href
                location.href="http://localhost:3000/login.html?back="+url
            }
        },
        getCarCount(){ 
                axios.get("http://localhost:3000/cart/getCount")
                .then((res)=>{
                    this.carCount=res.data[0].count
                })  
        },
        navItemOne(){
            location.reload(true)
        },
        navItemTwo(){
            location.href="http://localhost:3000/product-cake.html"
        },
        navItemThree(){
            location.href="http://localhost:3000/product-toast.html"
        },
        navItemFour(){
            location.href="http://localhost:3000/product-gift.html"
        },
        navItemFive(){
            location.href="http://localhost:3000/user.html"
        },
        CLUB(){},
        card(){},
    //轮播模块
         //获取轮播图片
         getImg(){
            axios.get("http://localhost:3000/banner/getBannerImg")
            .then((res)=>{
                res=res.data
                res.push(res[0])
                var len=res.length
                res[len-1].banner_id=len
                this.list=res
                this.loadBanner=true
                this.getProTitle()
                this.startCarousel(this.intervalTime) 
            })
        },
        //设置鼠标移到左右键时，轮播效果停止
        carouselOver(){
            this.isHover=true
        },
        carouselOut(){
            this.isHover=false
        },
        //设置轮播效果
        startCarousel(i){
            var len=this.list.length
            //窗口大小变动事件
            var width=document.body.clientWidth
            window.onresize=()=>{
                width=document.body.clientWidth
                    this.time=0
                    this.left=-width*this.pno
                    this.nextLeft=this.left
            }
            //轮播效果
            setInterval(()=>{
                if(document.visibilityState != 'hidden' && !this.isHover){
                    width=document.body.clientWidth
                    this.time=this.transitionTime
                    this.nextLeft += -width
                    if(this.nextLeft==-(len)*width){
                        this.nextLeft=-width
                    }
                    this.left=this.nextLeft
                    setTimeout(()=>{
                        this.time=0
                    },this.time/2)
                    this.pno++
                    if(this.pno==6){
                        this.time=this.left=this.nextLeft=this.pno=0
                        setTimeout(()=>{
                            this.time=this.transitionTime
                            this.left=this.nextLeft=-width
                            this.pno=1
                        },100)
                    }
                }
            },i)
        },
        //上一个图片
        carouselPrev(){
            var len=this.list.length
            var width=document.body.clientWidth
            if(this.pno==0){
                this.time=0
                this.pno=len-1
                this.left=-width*(this.pno)
                this.nextLeft=this.left
                setTimeout(()=>{
                    this.time=this.transitionTime
                    this.carouselPrev()
                },100)
            }else{
                this.pno--
                this.time=this.transitionTime
                this.left=-width*(this.pno)
                this.nextLeft=this.left
            }
        },
        //下一个图片
        carouselNext(){
            var len=this.list.length
            var width=document.body.clientWidth
            if(this.pno==(len-1)){
                this.time=this.left=this.nextLeft=this.pno=0
                setTimeout(()=>{
                    this.time=this.transitionTime
                    this.left=this.nextLeft=-width
                    this.pno=1
                },100)
            }else{
                this.pno++
                this.time=this.transitionTime
                this.left=-width*(this.pno)
                this.nextLeft=this.left
            }
        },
    //商品模块
        getProTitle(){
            axios.get("http://localhost:3000/product/title")
            .then((res)=>{
                var res=res.data
                this.proTitle=res
                this.getProList()
            })
        },
        getProList(){
            axios.get("http://localhost:3000/product/list")
            .then((res)=>{
                this.proList=res.data
                this.loadProduct=true;
                this.getToastList()
            })
        },
    //...吐司
        getToastList(){
            axios.get("http://localhost:3000/product/toastList")
            .then((res)=>{
                this.toastList=res.data
                this.loadF1=true
                this.getGiftList() 
            })
        },
    //礼品
        getGiftList(){
            axios.get("http://localhost:3000/product/giftList")
            .then((res)=>{
                this.giftList=res.data
                this.loadF2=true
                this.loadComment=true
                this.loadFooter=true
            })
        },
    //加入购物车
        addCart(i){
            
            var id=i
            axios.get("http://localhost:3000/product/proSpec?id="+id)
            .then((res)=>{
                var res=res.data
                if(res==-1){
                    alert("商品编号错误")
                }
                this.isaddcart=true
                this.cartBg=true
                this.carCake=res
            })
        },
        closeCart1(){
            this.isaddcart=false
            this.cartBg=false
        },
        goaddCart(i){
            var id=i
            axios.post("HTTP://localhost:3000/cart/addCar",Qs.stringify({
                pid:id
            }))
            .then((res)=>{
                if(res.data.code==1){
                    this.isaddcart=false
                    this.success=true
                    this.carCount+=1
                }else{
                    this.isaddcart=false
                    this.cartBg=false
                    alert("请先登录")
                    var url=location.href
                    location.href="http://localhost:3000/login.html?back="+url
                }
            })
        },
        closeCart2(){
            this.success=false
            this.cartBg=false
        },
        account(){
            this.success=false
            this.cartBg=false
            location.href="http://localhost:3000/shopping-car.html"
        },
        ToastCart(i){
            if(this.isLogin==false){
                alert("请先登录")
                var url=location.href
                location.href="http://localhost:3000/login.html?back="+url
            }else{
                this.success=true
                this.cartBg=true  
            }
        },
        GiftCart(i){
            if(this.isLogin==false){
                alert("请先登录")
                var url=location.href
                location.href="http://localhost:3000/login.html?back="+url
            }else{
                this.success=true
                this.cartBg=true  
            }
        }
    }
})